name: Validate Docker builds

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  validate-build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ci-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build --pull --tag "$IMAGE_TAG" .

      - name: Run container smoke test
        run: |
          output=$(docker run --rm "$IMAGE_TAG")
          echo "Container output: $output"
          if [ "$output" != "Hello, World!" ]; then
            echo "Unexpected container output"
            exit 1
          fi
