name: Publish Docker Images

on:
  workflow_call:
    inputs:
      release-tag:
        required: true
        type: string
      use-release-artifact:
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download release manifest
        if: inputs.use-release-artifact == true
        uses: actions/download-artifact@v4
        with:
          name: release-files

      - name: Apply release manifest
        if: inputs.use-release-artifact == true
        run: |
          cp release-files/package.json .
          cp release-files/package-lock.json .
          if [ -f release-files/CHANGELOG.md ]; then
            cp release-files/CHANGELOG.md .
          fi

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ inputs.release-tag }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
